name: Mirroring to remote repos
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  mirroring:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: mirror to gitlab.com
        uses: jee-r/docker-git-mirror@v1
        with:
          remote_repo: "gitlab.com/jee-r/dotfiles.git"
          remote_repo_username: ${{ secrets.GITLAB_USER }}
          remote_repo_password: ${{ secrets.GITLAB_TOKEN }}
      - name: mirror to framagit
        uses: jee-r/docker-git-mirror@v1
        with:
          remote_repo: "framagit.org/jee/dotfiles.git"
          remote_repo_username: ${{ secrets.FRAMAGIT_USER }}
          remote_repo_password: ${{ secrets.FRAMAGIT_TOKEN }}
